responsive_share_buttons.settings:
  type: config_object
  label: 'Responsive Share Buttons settings'
  mapping:
    twitter_name:
      type: string
      label: 'Twitter user name'
    networks:
      type: sequence
      label: 'Social Networks'
      sequence:
        id:
          type: string
        active:
          type: boolean
        weight:
          type: integer
